### ISSUE TITLE
可以共享下你的comfyui 流程？

### ISSUE THREAD

**Issue by laik** [StartHua/Comfyui_leffa#3]
安装完后找不到对应节点，谢谢 ！！

**Comment by StartHua** [comment]
里面有工作流，如果节点失败看你依赖按了没

**Comment by laik** [comment]
按照你提供的图编辑了个
[leffa.json](https://github.com/user-attachments/files/18197664/leffa.json)
<img width="1374" alt="image" src="https://github.com/user-attachments/assets/e124a763-618c-4615-a70b-097490b099a6" />
